package com.gu.devenv

import scala.util.{Failure, Success}
import java.nio.file.Paths
import fansi.{Bold, Color}

/** Natively compiled tool that wraps the Scala logic in a CLI program.
  */
object Main {
  def main(args: Array[String]): Unit =
    args.headOption match {
      case Some("init")     => init()
      case Some("generate") => generate()
      case Some("check")    => check()
      case Some("help" | "--help" | "-h") =>
        printUsage()
      case Some(unknown) =>
        System.err.println(Color.Red(s"Unknown command: $unknown"))
        printUsage()
        sys.exit(1)
      case None =>
        System.err.println(Color.Red("No command provided."))
        printUsage()
        sys.exit(1)
    }

  private def printUsage(): Unit = {
    val header   = Bold.On("Usage:") ++ " devenv " ++ Color.Cyan("<command>")
    val commands = Bold.On("Commands:")
    val init     = Bold.On(Color.Cyan("init"))
    val generate = Bold.On(Color.Cyan("generate"))
    val check    = Bold.On(Color.Cyan("check"))

    println(
      s"""$header
         |
         |$commands
         |  $init      Initialize .devcontainer directory structure
         |  $generate  Generate devcontainer.json files from .devenv config
         |  $check     Ensure devcontainer.json files match current config
         |""".stripMargin
    )
  }

  /** Sets up a .devcontainer directory with nested subdirectories.
    *
    * Uses the project's devenv configuration file to generate:
    *   - .devcontainer/user/ (for user-specific devcontainer with merged preferences)
    *   - .devcontainer/shared/ (for project-specific devcontainer that can be checked in)
    *   - .devcontainer/.gitignore (to exclude user directory)
    *   - .devcontainer/devenv.yaml (project-specific configuration file)
    *
    * The devcontainer.json files can be generated by running the generate command after populating
    * the project's `devenv.yaml` settings file.
    */
  def init(): Unit = {
    val devcontainerDir = Paths.get(".devcontainer")

    Devenv.init(devcontainerDir) match {
      case Success(result) =>
        println(Output.initResultMessage(result))
      case Failure(exception) =>
        System.err.println(s"Initialization failed: ${exception.getMessage}")
        exception.printStackTrace()
        sys.exit(1)
    }
  }

  /** Generates two devcontainer files for the current project, using the provided devenv
    * configuration.
    *
    * A user-specific file that includes properties merged from the users' own system-wide devenv
    * settings, and a generic user-agnostic devcontainer file that can be checked into the repo and
    * used for remote cloud devcontainers.
    */
  def generate(): Unit = {
    val devcontainerDir = Paths.get(".devcontainer")
    val userConfigPath =
      Paths.get(System.getProperty("user.home"), ".config", "devenv")

    Devenv.generate(devcontainerDir, userConfigPath) match {
      case Success(result) =>
        println(Output.generateResultMessage(result))
      case Failure(exception) =>
        System.err.println(s"Generation failed: ${exception.getMessage}")
        exception.printStackTrace()
        sys.exit(1)
    }
  }

  /** Checks whether the saved devcontainer.json files match what would be generated from the
    * current configuration.
    *
    * Validates that both user and shared devcontainer files are up-to-date with the current
    * devenv.yaml configuration. Useful for CI/CD to ensure configs are synchronized.
    */
  def check(): Unit = {
    val devcontainerDir = Paths.get(".devcontainer")
    val userConfigPath =
      Paths.get(System.getProperty("user.home"), ".config", "devenv")

    Devenv.check(devcontainerDir, userConfigPath) match {
      case Success(result) =>
        println(Output.checkResultMessage(result))
        result match {
          case CheckResult.Match(_, _) =>
            sys.exit(0)
          case CheckResult.Mismatch(_, _, _, _) =>
            sys.exit(1)
          case CheckResult.NotInitialized =>
            sys.exit(1)
        }
      case Failure(exception) =>
        System.err.println(s"Check failed: ${exception.getMessage}")
        exception.printStackTrace()
        sys.exit(1)
    }
  }
}
